=== プライベートレジストリ

プライベートレジストリをデプロイすることができます。

レジストリには、 https://docs.docker.com/registry/[Docker Registry] を使用します。

また、コンテナイメージを格納するために Persistent Volume が必要です。
Rook / NFS または Rook / Ceph をデプロイしている場合は、これをそのまま使用できます。

==== 設定・デプロイ

プライベートレジストリを使用する場合は `inventory/group_vars/all/registry.yml` に設定を記述します。

```yaml
# Registry enabled?
registry_enabled: yes

# Registry type: static-pod or pv
registry_type: pv

# Auth user
registry_user: registry

# Auth password
registry_password: registry

# Registry image version
#registry_version: 2.7.1

# PVC storage class name
#registry_pvc_storage_class: rook-nfs-share1  # Default to use rook-nfs
registry_pvc_storage_class: rook-ceph-block  # Use rook-ceph block storage

# PVC storage size
registry_pvc_size: 10Gi
```

* registry_enabled: レジストリを有効にします。yes に設定してください。
* registry_type: レジストリタイプを指定します。'pv' を指定してください。デフォルトは 'pv' です。
* registry_user: レジストリ認証ユーザ名を指定します。適宜変更してください。
* registry_password: レジストリ認証パスワードを指定します。適宜変更してください。
* registry_pvc_storage_class: 使用する PV のストレージクラスを指定します。
** <<_rook_nfs, Rook / NFS>> を使用する場合は `rook-nfs-share1` を指定してください。
** <<_rook_ceph, Rook / Ceph>> を使用する場合は `rook-ceph-block` を指定してください。
* registry_pvc_size: レジストリとして確保する PV のサイズを指定してください。

以下手順でデプロイを行ってください。

    $ ansible-playbook -i inventory/hosts apps.yml --tags=registry

==== レジストリの使用

レジストリは Node Port service として export されます。
以下手順でポート番号を確認してください。

    $ kubectl -n registry get svc

レジストリの URL は `https://[node]:[nodeport]` となります。
ここで、node はいずれかのノードのアドレス/ホスト名、nodeport は上記で確認した NodePort のポート番号です。

以下手順で login 可能です。

    $ docker login https://[node]:[nodeport]
