== Kubernetes Installation Overview

=== Installation Instructions

There are three different installation procedures. We recommend using the Ansible installer.

. Manual Installation: Manual installation using https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/[kubeadm]
** These instructions are provided as a reference only. Normally, you can use the `k8s-installer` installer to perform an automated installation using
** Please see <<manual_install>> for details.
. Script Installer: Automatic installation using the sh script-based installer
** Standalone and single-master configurations are supported.
** This installer is a simplified version and only sets up the Kubernetes cluster (no applications are installed).
** See <<script_installer>> for details.
. Ansible installer.
** Automatic cluster batch installation using Ansible.
** Deploys networking, storage, and applications as well as Kubernetes.
** See <<ansible_installer>> for more information.

The script installer and Ansible installer also supports offline installation.
In offline installation, all the files required for the installation are obtained on a machine connected to the Internet,
and then transferred to the target machines using a USB memory stick or hard disk.

NOTE: Only the ansible installer is suppported for RHEL8 / CentOS8 / Ubuntu.

=== The installers

The scrip installer and ansible installer is included with https://github.com/k8s-installer/k8s-installer[k8s-installer].

You can download them from https://github.com/k8s-installer/k8s-installer/releases
