== Requirements

=== System Configuration

There are three system configurations for installing Kubernetes.
The number of machines required will vary depending on the configuration.

. Standalone: a configuration with only one machine.
** Use only one machine and install both Kubernetes master and worker on the machine.
** The workload will also run on the same machine.
** Recommended for use in development environments and for verification and demonstration purposes only.
. Single Master: one master and one or more workers
** A single master can be configured with multiple workers.
** The workload runs on the workers.
** The master node will be a SPOF and is not recommended for use in a production environment.
. HA configuration: 3 masters and 1 or more workers.
** HA is configured with three masters.
** L4 load balancer is required separately because it is necessary to distribute the load to the kube-apiserver running on the master.

To create an HA configuration, you need at least three machines as master nodes.
In addition, you need at least one worker node, and at least three recommended.
The number of worker nodes depends on the amount of workloads to be executed.

=== Required machine

This section describes each of the machines that make up Kubernetes.

The following requirements are almost same as described in
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/[Installing kubeadm].

==== OS

Machines with one of the following operating systems installed is required:

* RedHat Enterprise Linux (RHEL) 7 (7.7 or later), 8
** You must have completed registration of your RedHat subscription using `subscription-manager`.
* CentOS 7 (7.7 or later), 8
* Ubuntu 18.04, 20.04

NOTE: Only the ansible installer is supported for RHEL8 / CentOS8 / Ubuntu.

WARNING: You can't use firewalld for RHEL8 / CentOS8.

==== Hardware spec

The machine specs require the following.

* 2 GB or more of RAM per machine
** any less will leave little room for your apps)
* 2 CPUs or more

==== Network

For the network, the following requirements are required

* Full network connectivity between all machines in the cluster
** public or private network is fine
* Internet connectivity
** A connection through a proxy server is fine.
** For offline installation, no Internet connection is required. However, the default route must still be configured.

==== Other requirements

* Unique hostname, MAC address, and product_uuid for every node.
** The hostname can be checked with the `hostname` command.
** You can get the MAC address of the network interfaces using the command `ip link` or `ifconfig -a`.
** The product_uuid can be checked by using the command `sudo cat /sys/class/dmi/id/product_uuid`.
** For more information, See "Verify the MAC address and product_uuid are unique for every node" section in
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/[Installing kubeadm].
* Certain ports are open on your machines. See here for more details.
** For more information on the ports to be opened, see "Check required ports" section of
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/[Installing kubeadm].
** If you use the installer, the firewall is automatically configured.
** If you use the installer, it will automatically configure the firewall for you.
* Swap disabled.
** You MUST disable swap in order for the kubelet to work properly.
** If you use an installer, Swap is automatically turned off.

=== Load balancer

When configuring HA configuration, an L4(TCP) level load balancer is required.

* The load balancer must have a DNS-resolvable FQDN name.
* Load balancing at the L4 level
** Load balancing TCP port 6443 to same ports of the master node (three nodes).
** Perform health checks on TCP connections.
