[[rook_nfs]]
=== Rook / NFS

Rook + NFS (Network File System) を使用することができます。

NFSサーバは Kubernetes クラスタ上の Pod として起動されます。
ストレージは、指定した特定の1台のノード上のストレージ(local volume)を使用し、
このノード上でNFSサーバ Pod を起動するように設定されます。

詳細は Rook Documentation の https://rook.github.io/docs/rook/master/nfs.html[NFS] を参照してください。

WARNING: 本設定では特定の1つのノード上のストレージを使用するため、可用性はありません。

==== 設定・デプロイ

NFS を使用する場合は `inventory/group_vars/all/storage.yml` に設定を記述します。
例を示します。

```yaml
#----------------------------------------------------------
# rook-nfs config
#----------------------------------------------------------

# rook-nfs Enabled?
rook_nfs_enabled: yes

# Hostname hosts NFS PV local volume
rook_nfs_pv_host: "worker-1"

# NFS local volume size
#rook_nfs_pv_size: 10Gi

# NFS local volume dir on host
#rook_nfs_pv_dir: /var/lib/rook-nfs
```

* rook_nfs_enabled: NFS を使用する場合、yes に設定してください。
* rook_nfs_pv_host: Local Volume PV を作成するノード名を指定してください。
** Inventory に記載されたノード名のいずれか1つを指定してください。
** 指定したノード上に NFS サーバストレージが確保されます。また NFS サーバ Pod もこのノード上で動作します。
** 指定したノードは Schedulable である必要があります。
* rook_nfs_pv_size: Local Volume のサイズ(NFSサーバとして使用するストレージサイズ)を指定します。デフォルトは 10Gi です。
* rook_nfs_pv_dir: Local Volume を作成するディレクトリを指定します。デフォルトは /var/lib/rook-nfs です。

以下手順でデプロイを行ってください。

    $ ansible-playbook -i inventory/hosts apps.yml --tags=rook-nfs

==== ストレージクラス

本 NFS サーバに対応するストレージクラスとして、`rook-nfs-share1` が追加されます。

本ストレージを使用するための Persistent Volume Claim (PVC) の例を示します。

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim
spec:
  storageClassName: rook-nfs-share1
  accessModes:
    - ReadWriteMany
  resources:
  requests:
    storage: 100Mi
```
