=== Requirements

Ansible 2.9 or higher must be installed on the Ansible node.

You need to be able to log in via ssh from the Ansible node to all master and worker nodes.
In this case, the following conditions are required.

* You must be able to make an ssh connection from the Ansible node to each node with public key authentication.
** Do not use root as the login user.
** It is recommended that the login user name be the same on all machines.
** Password authentication cannot be used. Use only public key authentication.
* No passphare input is required when perform public key authentication.
** If you have a passphrase set, you must use ssh-agent.
* You must be able to run sudo as the logged-in user after you ssh login to each node from the Ansible node.

==== Instructions for setting up ssh public key authentication

If you don't already have an ssh key pair on the Ansible node, follow these steps to create it.
~/.ssh/id_rsa, ~/.ssh/id_rsa.pub will be generated.

    $ ssh-keygen

On the Ansible node, perform the following steps for each master/worker node to enable login with public key authentication.
The public key will be added to ~/.ssh/authorized_keys on each node.

    $ ssh-copy-id [hostname]

==== ssh-agent

If you set a passphrase for your ssh key (and you should for security reasons),
you should use ssh-agent to be able to login using ssh without passphrase.

There are a number of ways to start ssh-agent, but the easiest way is to run the following on the Ansible node:

    $ exec ssh-agent $SHELL

Set your passphrase to ssh-agent as follows.

    $ ssh-add

Logging out will cause ssh-agent to exit, so this procedure must be performed each time you log in to the Ansible node.

==== Ansible installation instructions

Create a Python virtual environment on an Ansible node.
Use Python 2 + https://virtualenv.pypa.io/en/latest/[virtualenv]
or Python 3 + https://docs. python.org/en/3/library/venv.html[venv].

Here's an example of how to create a virtual environment in the case of Python2 + virtualenv:

    $ sudo yum install python-virtualenv
    $ virtualenv $HOME/venv

Here's an example of how to create a virtual environment for Python 3 + venv:

    $ sudo subscription-manager repos --enable rhel-7-server-optional-rpms  # RHEL7の場合
    $ sudo yum install python3 python3-pip gcc openssl-devel python3-devel
    $ python3 -m venv $HOME/venv

Activate the virtual environment as follows:

    $ . $HOME/venv/bin/activate

Follow the steps below to install Ansible.

    $ pip install -U -r requirements.txt

If you need to install Ansible on an Ansible machine in an offline environment, use
https://github.com/tmurakam/python-offline-env[python-offline-env].
