[[script_installer]]
== スクリプトインストーラ

スクリプトインストーラを使用したインストール手順について説明します。
スクリプトインストーラは `k8s-installer` の `script` ディレクトリに格納されています。

スクリプトインストーラを使用する場合は、各マシン上にインストーラを展開し、各マシン上でそれぞれインストール
作業を行う必要があります。

=== 設定

`config.sample.sh` を `config.sh` にコピーし、設定を行ってください。

* HA構成にする場合:
** ロードバランサのDNS名(FQDN)とポート番号をを `LOAD_BALANCER_DNS`, `LOAD_BALANCER_PORT` に指定してください。
** ロードバランサは、指定したポートを全マスターノードにL4負荷分散するよう設定しておく必要があります。
** 詳細は https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/high-availability/[kubeadmを使用した高可用性クラスターの作成] を参照してください。
* Internet接続に Proxy を経由する必要がある場合は、`PROXY_URL`, `NO_PROXY` の値を設定してください。
** NO_PROXY には必ず kube-apiserver の IPアドレスまたはDNS名を指定しなければなりません。
シングルホストの場合はマスターノードの、HA構成の場合はロードバランサの値を指定してください。
これが適切に設定されていないとマスターノードのインストールが失敗します。
* オフラインインストールを行う場合は、`OFFLINE_INSTALL` を `yes` に設定してください。詳細は後述します。

=== Docker / kubeadm インストール

Docker, kubeadm などをインストールします。

本手順はマスター・ワーカー全マシン上でそれぞれ行う必要があります。

sudo 可能な一般ユーザ権限でログインしてください(root での直接ログインは不可)。
以下手順でインストールを実行してください。

    $ sudo ./install-common.sh

=== マスターノードのインストール

マスターノードに Kubernetes マスターコントロールプレーンをインストールします。

マスターノード(HA構成の場合は1台目のマスターノード)にログインし、以下手順を実行してください。

    # シングルマスター構成の場合
    $ sudo ./install-master-single.sh

    # HA構成の場合(1台目のマスターノード)
    $ sudo ./install-master-ha.sh

インストールには数分かかります。
画面にワーカーノードを join するための `kubeadm join` コマンドラインが表示されるので、メモしてください。

インストールが完了したら、以下手順で ~/.kube/config をインストールします。

    $ ./install-kubeconfig.sh

`kubectl cluster-info` を実施し、正常にコントロールプレーンが動作していることを確認します。

最後に calico ネットワークアドオンをインストールします。

    $ ./install-cni.sh

=== HA構成: 残りのマスターノードのインストール

HA構成の2台目以降のマスターノードのインストール手順は、
https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/high-availability/[kubeadmを使用した高可用性クラスターの作成]
の「残りのコントロールプレーンノードの手順」を参照してください。

=== ワーカーノードのインストール

各ワーカーノードにログインし、上記取得した `kubeadm join` コマンドを sudo 付きで実行し、
ノードを Kubernetes クラスタに参加させてください。

=== インストール後の確認

マスターノード上で `kubectl get nodes` を実行し、全ノードが追加されていて Ready になっていることを確認してください。

また、`kubectl get all -n kube-system` を実行し、Podがすべて正常に起動していることを確認してください。
