=== インストール

==== 共通処理

以下手順を実行し、全ノード共通の事前処理を実行します。
本手順により、オフラインリポジトリ設定、Proxy設定、必要なパッケージ(Docker/kubeadm含む)のインストール、
共通のコンフィグレーション処理、などが実行されます。

    $ ansible-playbook -i inventory/hosts common.yml -K

NOTE: ログイン先マシンで `sudo` パスワードが不要な場合は -K (--ask-become-pass) オプションを省略できます。

==== 1台目のマスターノードへの Kubernetes デプロイ

以下を実行し、1台目のマスターノードへ Kubernetes マスターをインストールします。

    $ ansible-playbook -i inventory/hosts master-first.yml -K

この時点で Kubernetes はシングルノードで動作している状態になります。
当該ホストに ssh ログインし、`kubectl get all --all-namespaces` を実行すれば、各種 Pod が稼働していることを確認できます。

==== 2台目以降のマスターノードへのデプロイ

以下を実行し、2台目以降のノードを Kubernetes クラスタにマスターノードとして参加させます。

    $ ansible-playbook -i inventory/hosts master-secondary.yml -K

==== ワーカーノードへのデプロイ

以下を実行し、全ワーカーノードを Kubernetes クラスタに参加させます。

    $ ansible-playbook -i inventory/hosts worker.yml -K

==== アプリケーション類のデプロイ

以下を実行し、アプリケーション類(Ingress controller, metrics server, Rook など)をdプロイします。

    $ ansible-playbook -i inventory/hosts apps.yml -K

==== 補足: 全手順を一括で行う方法

以下手順を実行することで、上記の全手順を一括で行うことも可能です。
通常は順を追って１ステップずつ実行することをお勧めします。

    $ ansible-playbook -i inventory/hosts site.yml -K
