=== 必要環境

Ansibleノードに Ansible 2.9 以上をインストールする必要があります。

Ansibleノードから全マスターノード・ワーカーノードに対して ssh でログインできる必要があります。
この際、以下の条件が必要です。

* Ansibleノードから各ノードに対して公開鍵認証で ssh 接続が可能であること。
** この際、ログインユーザとして root は使用しないでください。
** ログインするユーザ名は全マシンで同一にすることを推奨します。
** パスワード認証は使用できません。必ず公開鍵認証を使用してください。
* 公開鍵認証を行う際、パスフレーズの入力が不要であること。
** パスフレーズを設定している場合、ssh-agent を使用する必要があります。
* Ansibleノードから各ノードに対して ssh ログインしたあと、ログインユーザで sudo を実行可能であること。

==== ssh 公開鍵認証のセットアップ手順

Ansibleノード上に ssh 鍵ペアがまだない場合は、以下手順で作成してください。
~/.ssh/id_rsa, ~/.ssh/id_rsa.pub が生成されます。

    $ ssh-keygen

Ansibleノード上で、各マスターノード・ワーカーノード毎に以下手順を実行し公開鍵認証でログインできるようにします。
公開鍵は各ノードの ~/.ssh/authorized_keys に追加されます。

    $ ssh-copy-id [hostname]

==== ssh-agent

ssh 鍵にパスフレーズを設定している場合は(セキュリティ上パスフレーズは設定すべきです)、
ssh-agent を使用してパスフレーズ入力無しで ssh ログインできるようにする必要があります。

ssh-agent の起動方法はいくつかありますが、最も簡単な方法は Ansibleノードで以下を実行する方法です。

    $ exec ssh-agent $SHELL

以下手順でパスフレーズを ssh-agent に設定してください。

    $ ssh-add

ログアウトすると ssh-agent は終了しますので、本手順はAnsibleノードへのログインの度に毎回実行する必要があります。

==== Ansible のインストール手順

Ansibleノード上でPython 仮想環境を作成してください。
Python 2 + https://virtualenv.pypa.io/en/latest/[virtualenv] または
Python 3 + https://docs.python.org/ja/3/library/venv.html[venv] を使用します。

Python2 + virtualenv の場合の仮想環境作成例を示します。

    $ sudo yum install python-virtualenv
    $ virtualenv $HOME/venv

Python 3 + venv の場合の仮想環境作成例を示します。

    $ sudo subscription-manager repos --enable rhel-7-server-optional-rpms  # RHEL7の場合
    $ sudo yum install python3 python3-pip gcc openssl-devel python3-devel
    $ python3 -m venv $HOME/venv

以下手順で仮想環境を activate します。

    $ . $HOME/venv/bin/activate

以下手順で Ansible をインストールしてください。

    $ pip install -U -r requirements.txt

オフライン環境の Ansible マシンに Ansible をインストールする必要がある場合は
https://github.com/tmurakam/python-offline-env[python-offline-env] を使用してください。
