=== Renewal of certificates

Kubernetes server and client certificates are valid for one year, so you have to renew your certificates periodically.

For more information, see https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/[Certificate Management with kubeadm].

==== Automatic renewal of certificates

When you upgrade Kubernetes, kubeadm will automatically update your certificates.
Kubernetes gets a minor upgrade every few months, so if you upgrade regularly in conjunction with this, your certificate will not expire.
(It is a best practice to upgrade your cluster frequently in order to stay secure.)

==== Verification of Certificate Expiration Date

You can check the expiration date by performing the following procedure on each master node.

    $ sudo kubeadm alpha certs check-expiration

==== Manual certificate update

You can manually update your certificate by following the steps below.

===== If you are using the Ansible installer

You can use the `renew-server-certs` playbook to manually update the certificates on all master nodes.
All certificates are regenerated with an expiration date of one year.

    $ ansible-playbook -i inventory/hosts renew-server-certs.yml

===== If you are using the script based installer

Perform the following procedures on all master nodes.

    $ sudo kubeadm alpha certs renew all
    $ sudo /bin/rm /var/lib/kubelet/kubelet.crt
    $ sudo /bin/rm /var/lib/kubelet/kubelet.key
    $ sudo systemctl restart kubelet
